services:
  # https://hub.docker.com/_/nginx
  nginx:
    container_name: nginx
    image: nginx:1.26.2-alpine3.20-slim
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./htpasswd:/etc/nginx/htpasswd
